service: minimal-rs

# plugins:
#   - serverless-rust

provider:
  name: aws
  runtime: provided.al2
  region: eu-north-1

package:
  individually: true

functions:
  handler:
    handler: minimal-rs
